/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package entrada;

import com.sun.jdi.connect.spi.Connection;
import conexaobd.Agenda;
import conexaobd.Conexaobd;
import conexaobd.Paciente;
import java.beans.Statement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.spi.DirStateFactory.Result;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 3° Ano Info
 */
public class telaPrincipal extends javax.swing.JFrame {
        Paciente cadastrar = new Paciente();
        Paciente salvar = new Paciente();
        Conexaobd conexao = new Conexaobd();
        private String cpf;
    /**
     * Creates new form telaPrincipal
     */
    public telaPrincipal() {
        initComponents();
        listarValores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        telaprincipal = new javax.swing.JPanel();
        telaazulescuro = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        abaagenda = new javax.swing.JPanel();
        logoagenda = new javax.swing.JLabel();
        agendatexto = new javax.swing.JLabel();
        abapacientes = new javax.swing.JPanel();
        logopacientes = new javax.swing.JLabel();
        pacientestexto = new javax.swing.JLabel();
        abaprofissionais = new javax.swing.JPanel();
        logoprofissionais = new javax.swing.JLabel();
        profissionaistexto = new javax.swing.JLabel();
        abapaciente = new javax.swing.JPanel();
        textPaciente = new javax.swing.JLabel();
        textNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        textTelefoneouEmail = new javax.swing.JLabel();
        txtCpf1 = new javax.swing.JTextField();
        textAlergias = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        textDatadeNascimento = new javax.swing.JLabel();
        txtAlergias = new javax.swing.JTextField();
        textSexo = new javax.swing.JLabel();
        txtSexo = new javax.swing.JComboBox<>();
        textEndereco = new javax.swing.JLabel();
        listaPaciente = new javax.swing.JScrollPane();
        jTablePacientes = new javax.swing.JTable();
        textListadePaciente = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        textCPF = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jData1 = new javax.swing.JFormattedTextField();
        textNumeracao = new javax.swing.JLabel();
        txtNumeroD = new javax.swing.JTextField();
        fechar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        telaprincipal.setBackground(new java.awt.Color(138, 203, 222));

        telaazulescuro.setBackground(new java.awt.Color(9, 86, 122));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/Sem-Título-2 (1).png"))); // NOI18N

        abaagenda.setBackground(new java.awt.Color(21, 103, 141));
        abaagenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abaagendaMouseClicked(evt);
            }
        });

        logoagenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/agenda-dentaria.png"))); // NOI18N

        agendatexto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        agendatexto.setForeground(new java.awt.Color(255, 255, 255));
        agendatexto.setText("Agenda");

        javax.swing.GroupLayout abaagendaLayout = new javax.swing.GroupLayout(abaagenda);
        abaagenda.setLayout(abaagendaLayout);
        abaagendaLayout.setHorizontalGroup(
            abaagendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaagendaLayout.createSequentialGroup()
                .addComponent(logoagenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(agendatexto, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        abaagendaLayout.setVerticalGroup(
            abaagendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abaagendaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoagenda, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(agendatexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        abapacientes.setBackground(new java.awt.Color(21, 103, 141));

        logopacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/dentista.png"))); // NOI18N

        pacientestexto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pacientestexto.setForeground(new java.awt.Color(255, 255, 255));
        pacientestexto.setText("Pacientes");

        javax.swing.GroupLayout abapacientesLayout = new javax.swing.GroupLayout(abapacientes);
        abapacientes.setLayout(abapacientesLayout);
        abapacientesLayout.setHorizontalGroup(
            abapacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abapacientesLayout.createSequentialGroup()
                .addComponent(logopacientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pacientestexto, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        abapacientesLayout.setVerticalGroup(
            abapacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logopacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(pacientestexto, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
        );

        abaprofissionais.setBackground(new java.awt.Color(21, 103, 141));
        abaprofissionais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abaprofissionaisMouseClicked(evt);
            }
        });

        logoprofissionais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/Sem-Título-3.png"))); // NOI18N

        profissionaistexto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        profissionaistexto.setForeground(new java.awt.Color(255, 255, 255));
        profissionaistexto.setText("Prontuário");
        profissionaistexto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profissionaistextoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout abaprofissionaisLayout = new javax.swing.GroupLayout(abaprofissionais);
        abaprofissionais.setLayout(abaprofissionaisLayout);
        abaprofissionaisLayout.setHorizontalGroup(
            abaprofissionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaprofissionaisLayout.createSequentialGroup()
                .addComponent(logoprofissionais)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(profissionaistexto, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        abaprofissionaisLayout.setVerticalGroup(
            abaprofissionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaprofissionaisLayout.createSequentialGroup()
                .addComponent(logoprofissionais, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abaprofissionaisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(profissionaistexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout telaazulescuroLayout = new javax.swing.GroupLayout(telaazulescuro);
        telaazulescuro.setLayout(telaazulescuroLayout);
        telaazulescuroLayout.setHorizontalGroup(
            telaazulescuroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(abaagenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(telaazulescuroLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(logo)
                .addContainerGap(111, Short.MAX_VALUE))
            .addComponent(abapacientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(abaprofissionais, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        telaazulescuroLayout.setVerticalGroup(
            telaazulescuroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaazulescuroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo)
                .addGap(65, 65, 65)
                .addComponent(abaagenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(abapacientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(abaprofissionais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        abapaciente.setBackground(new java.awt.Color(192, 230, 240));

        textPaciente.setBackground(new java.awt.Color(9, 86, 122));
        textPaciente.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        textPaciente.setForeground(new java.awt.Color(9, 86, 122));
        textPaciente.setText("Pacientes");

        textNome.setBackground(new java.awt.Color(9, 86, 122));
        textNome.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        textNome.setForeground(new java.awt.Color(9, 86, 122));
        textNome.setText("Nome:");

        txtNome.setBackground(new java.awt.Color(192, 230, 240));
        txtNome.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtNome.setForeground(new java.awt.Color(9, 86, 122));
        txtNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(9, 86, 122)));
        txtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomeFocusGained(evt);
            }
        });

        textTelefoneouEmail.setBackground(new java.awt.Color(9, 86, 122));
        textTelefoneouEmail.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        textTelefoneouEmail.setForeground(new java.awt.Color(9, 86, 122));
        textTelefoneouEmail.setText("Telefone:");

        txtCpf1.setBackground(new java.awt.Color(192, 230, 240));
        txtCpf1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtCpf1.setForeground(new java.awt.Color(9, 86, 122));
        txtCpf1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(9, 86, 122)));
        txtCpf1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCpf1FocusGained(evt);
            }
        });

        textAlergias.setBackground(new java.awt.Color(9, 86, 122));
        textAlergias.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        textAlergias.setForeground(new java.awt.Color(9, 86, 122));
        textAlergias.setText("Alergias:");

        txtEndereco.setBackground(new java.awt.Color(192, 230, 240));
        txtEndereco.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtEndereco.setForeground(new java.awt.Color(9, 86, 122));
        txtEndereco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(9, 86, 122)));
        txtEndereco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEnderecoFocusGained(evt);
            }
        });

        textDatadeNascimento.setBackground(new java.awt.Color(9, 86, 122));
        textDatadeNascimento.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        textDatadeNascimento.setForeground(new java.awt.Color(9, 86, 122));
        textDatadeNascimento.setText("Data de nascimento:");

        txtAlergias.setBackground(new java.awt.Color(192, 230, 240));
        txtAlergias.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtAlergias.setForeground(new java.awt.Color(9, 86, 122));
        txtAlergias.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(9, 86, 122)));
        txtAlergias.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAlergiasFocusGained(evt);
            }
        });
        txtAlergias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlergiasActionPerformed(evt);
            }
        });

        textSexo.setBackground(new java.awt.Color(9, 86, 122));
        textSexo.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        textSexo.setForeground(new java.awt.Color(9, 86, 122));
        textSexo.setText("Sexo:");

        txtSexo.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtSexo.setForeground(new java.awt.Color(9, 86, 122));
        txtSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Feminino", "Masculino", "Outros" }));
        txtSexo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(9, 86, 122)));

        textEndereco.setBackground(new java.awt.Color(9, 86, 122));
        textEndereco.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        textEndereco.setForeground(new java.awt.Color(9, 86, 122));
        textEndereco.setText("Endereço:");

        jTablePacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome do paciente", "CPF", "Endereço", "N° do dente", "Data de nascimento", "Sexo", "Alergias", "Telefone"
            }
        ));
        listaPaciente.setViewportView(jTablePacientes);

        textListadePaciente.setBackground(new java.awt.Color(9, 86, 122));
        textListadePaciente.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        textListadePaciente.setForeground(new java.awt.Color(9, 86, 122));
        textListadePaciente.setText("Lista de pacientes");

        txtTelefone.setBackground(new java.awt.Color(192, 230, 240));
        txtTelefone.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtTelefone.setForeground(new java.awt.Color(9, 86, 122));
        txtTelefone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(9, 86, 122)));
        txtTelefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTelefoneFocusGained(evt);
            }
        });

        textCPF.setBackground(new java.awt.Color(9, 86, 122));
        textCPF.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        textCPF.setForeground(new java.awt.Color(9, 86, 122));
        textCPF.setText("CPF:");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(9, 86, 122));
        jLabel3.setText("               Salvar");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(9, 86, 122)));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(9, 86, 122));
        jLabel4.setText("               Alterar");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(9, 86, 122)));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(9, 86, 122));
        jLabel9.setText("               Deletar");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(9, 86, 122)));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(9, 86, 122));
        jLabel5.setText("   Confirmar alteração");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(9, 86, 122)));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        try {
            jData1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        textNumeracao.setBackground(new java.awt.Color(9, 86, 122));
        textNumeracao.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        textNumeracao.setForeground(new java.awt.Color(9, 86, 122));
        textNumeracao.setText("N° do dente");

        txtNumeroD.setBackground(new java.awt.Color(192, 230, 240));
        txtNumeroD.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtNumeroD.setForeground(new java.awt.Color(9, 86, 122));
        txtNumeroD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(9, 86, 122)));
        txtNumeroD.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNumeroDFocusGained(evt);
            }
        });

        javax.swing.GroupLayout abapacienteLayout = new javax.swing.GroupLayout(abapaciente);
        abapaciente.setLayout(abapacienteLayout);
        abapacienteLayout.setHorizontalGroup(
            abapacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abapacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abapacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abapacienteLayout.createSequentialGroup()
                        .addGroup(abapacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abapacienteLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(338, 338, 338))
                            .addGroup(abapacienteLayout.createSequentialGroup()
                                .addComponent(textNome)
                                .addGap(518, 518, 518))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abapacienteLayout.createSequentialGroup()
                                .addGroup(abapacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textCPF)
                                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCpf1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(abapacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(abapacienteLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(abapacienteLayout.createSequentialGroup()
                                        .addGroup(abapacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textEndereco)
                                            .addComponent(textNumeracao)
                                            .addComponent(txtNumeroD, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(36, 36, 36)
                                        .addGroup(abapacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textDatadeNascimento)
                                            .addComponent(textSexo)
                                            .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jData1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(26, 26, 26)))
                        .addGroup(abapacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textTelefoneouEmail)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textAlergias)
                            .addComponent(txtAlergias, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 87, Short.MAX_VALUE))
                    .addGroup(abapacienteLayout.createSequentialGroup()
                        .addGroup(abapacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(abapacienteLayout.createSequentialGroup()
                                .addComponent(textPaciente)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(listaPaciente))
                        .addContainerGap())))
            .addGroup(abapacienteLayout.createSequentialGroup()
                .addGap(273, 273, 273)
                .addComponent(textListadePaciente)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        abapacienteLayout.setVerticalGroup(
            abapacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abapacienteLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(textPaciente)
                .addGap(18, 18, 18)
                .addGroup(abapacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNome)
                    .addComponent(textEndereco)
                    .addComponent(textDatadeNascimento)
                    .addComponent(textAlergias))
                .addGap(1, 1, 1)
                .addGroup(abapacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(abapacienteLayout.createSequentialGroup()
                        .addGroup(abapacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAlergias, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                            .addComponent(jData1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(abapacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textSexo)
                            .addComponent(textTelefoneouEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(abapacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(abapacienteLayout.createSequentialGroup()
                        .addGroup(abapacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                            .addComponent(txtEndereco))
                        .addGap(18, 18, 18)
                        .addGroup(abapacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textCPF)
                            .addComponent(textNumeracao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(abapacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCpf1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumeroD, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(abapacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textListadePaciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listaPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        fechar.setBackground(new java.awt.Color(1, 89, 146));
        fechar.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        fechar.setForeground(new java.awt.Color(1, 89, 146));
        fechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/fechar-simbolo-de-botao-circular.png"))); // NOI18N
        fechar.setToolTipText("");
        fechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fecharMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout telaprincipalLayout = new javax.swing.GroupLayout(telaprincipal);
        telaprincipal.setLayout(telaprincipalLayout);
        telaprincipalLayout.setHorizontalGroup(
            telaprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaprincipalLayout.createSequentialGroup()
                .addComponent(telaazulescuro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(abapaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fechar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        telaprincipalLayout.setVerticalGroup(
            telaprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaprincipalLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(abapaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
            .addComponent(telaazulescuro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(telaprincipalLayout.createSequentialGroup()
                .addComponent(fechar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telaprincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telaprincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(1211, 632));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFocusGained
     
    }//GEN-LAST:event_txtNomeFocusGained

    private void txtCpf1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCpf1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpf1FocusGained

    private void txtEnderecoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEnderecoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoFocusGained

    private void txtAlergiasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAlergiasFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlergiasFocusGained

    private void txtTelefoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefoneFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneFocusGained
  Connection Con = null;
  Statement St = null;
  Result Rs = null;
  
     private void listarValores(){
        try {
          Paciente paciente = new Paciente();
          DefaultTableModel model = (DefaultTableModel) jTablePacientes.getModel();
          model.setNumRows(0);
          ArrayList<Paciente> lista = paciente.ListarPaciente();
          
          for(int num = 0 ; num < lista.size(); num++){
              model.addRow(new Object[]{
              lista.get(num).getNome(),
              lista.get(num).getCpf(),
              lista.get(num).getEndereco(),
              lista.get(num).getNumero_dente(),
              lista.get(num).getData_de_nascimento(),
              lista.get(num).getSexo(),
              lista.get(num).getAlergias(),
              lista.get(num).getTelefone()
              });
          }
        } catch (Exception ex){
            JOptionPane.showMessageDialog(null,"Listar Valores VIEW"+ ex);
        }
     }
    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
      cadastrar.cadPacientes(txtNome.getText(),txtCpf1.getText(),txtEndereco.getText(), txtNumeroD.getText(), jData1.getText(), txtSexo.getSelectedItem().toString(), txtAlergias.getText(), txtTelefone.getText());
      listarValores();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void abaagendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abaagendaMouseClicked
        new telaAgenda().setVisible(true);
    }//GEN-LAST:event_abaagendaMouseClicked

    private void abaprofissionaisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abaprofissionaisMouseClicked
        
    }//GEN-LAST:event_abaprofissionaisMouseClicked

    private void fecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fecharMouseClicked
        dispose();
    }//GEN-LAST:event_fecharMouseClicked

    private void profissionaistextoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profissionaistextoMouseClicked
            new telaProfissional().setVisible(true);
    }//GEN-LAST:event_profissionaistextoMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
      int setar = jTablePacientes.getSelectedRow();
        
      txtNome.setText(jTablePacientes.getModel().getValueAt(setar, 0).toString());
      txtCpf1.setText(jTablePacientes.getModel().getValueAt(setar, 1).toString());
      txtEndereco.setText(jTablePacientes.getModel().getValueAt(setar, 2).toString());
      txtNumeroD.setText(jTablePacientes.getModel().getValueAt(setar, 3).toString());
      jData1.setText(jTablePacientes.getModel().getValueAt(setar, 4).toString());
      txtSexo.setSelectedItem(jTablePacientes.getModel().getValueAt(setar, 5).toString());
      txtAlergias.setText(jTablePacientes.getModel().getValueAt(setar, 6).toString());
      txtTelefone.setText(jTablePacientes.getModel().getValueAt(setar, 7).toString());
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        int setar = jTablePacientes.getSelectedRow();
        cpf = jTablePacientes.getModel().getValueAt(setar,1).toString();
        Object[] options = { "Confirmar", "Cancelar" };
        int result = JOptionPane.showOptionDialog(null, "Tem certeza que deseja deletar esse paciente?", "Deletar paciente", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0])
;       
        if (result == JOptionPane.OK_OPTION){
        Paciente deletar = new Paciente();
        deletar.deletarPaciente(cpf);
        listarValores();
        }
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
       Paciente salvar = new Paciente();
       try{
           salvar.updPaciente(txtNome.getText(), txtCpf1.getText(), txtEndereco.getText(), txtNumeroD.getText(), jData1.getText(), (String) txtSexo.getSelectedItem(),txtAlergias.getText(), txtTelefone.getText());
           listarValores();
           JOptionPane.showMessageDialog(null, "Dados alterados com sucesso");
        
       } catch (Exception ex){
           System.out.println(ex);
       }    
    }//GEN-LAST:event_jLabel5MouseClicked

    private void txtAlergiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlergiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlergiasActionPerformed

    private void txtNumeroDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumeroDFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroDFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel abaagenda;
    public javax.swing.JPanel abapaciente;
    public javax.swing.JPanel abapacientes;
    public javax.swing.JPanel abaprofissionais;
    public javax.swing.JLabel agendatexto;
    public javax.swing.JLabel fechar;
    public javax.swing.JFormattedTextField jData1;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JTable jTablePacientes;
    public javax.swing.JScrollPane listaPaciente;
    public javax.swing.JLabel logo;
    public javax.swing.JLabel logoagenda;
    public javax.swing.JLabel logopacientes;
    public javax.swing.JLabel logoprofissionais;
    public javax.swing.JLabel pacientestexto;
    public javax.swing.JLabel profissionaistexto;
    public javax.swing.JPanel telaazulescuro;
    public javax.swing.JPanel telaprincipal;
    public javax.swing.JLabel textAlergias;
    public javax.swing.JLabel textCPF;
    public javax.swing.JLabel textDatadeNascimento;
    public javax.swing.JLabel textEndereco;
    public javax.swing.JLabel textListadePaciente;
    public javax.swing.JLabel textNome;
    public javax.swing.JLabel textNumeracao;
    public javax.swing.JLabel textPaciente;
    public javax.swing.JLabel textSexo;
    public javax.swing.JLabel textTelefoneouEmail;
    public javax.swing.JTextField txtAlergias;
    public javax.swing.JTextField txtCpf1;
    public javax.swing.JTextField txtEndereco;
    public javax.swing.JTextField txtNome;
    public javax.swing.JTextField txtNumeroD;
    public javax.swing.JComboBox<String> txtSexo;
    public javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables

    private void ConfirmarAlterar() throws ClassCastException {
           
                String nome, cpf, endereco, numeroD, data, sexo, alergias, telefone;
                nome = txtNome.getText();
                cpf = txtCpf1.getText();
                endereco = txtEndereco.getText();
                numeroD = txtNumeroD.getText();
                data = textDatadeNascimento.getText();
                sexo = txtSexo.toString();
                alergias = txtAlergias.getText();
                telefone = txtTelefone.getText();
                Paciente paciente = new Paciente();
                paciente.setNome(nome);
                paciente.setCpf(cpf);
                paciente.setEndereco(endereco);
                paciente.setNumero_dente(numeroD);
                paciente.setData_de_nascimento(data);
                paciente.setSexo(sexo);
                paciente.setAlergias(alergias);
                paciente.setTelefone(telefone);
                Paciente alterar = new Paciente();
                alterar.updPaciente(nome, cpf, endereco, numeroD,data, sexo, alergias, telefone);
                JOptionPane.showMessageDialog(null, "Cadastro editado com sucesso");
           
    
}
private void listarValoresAlunos() {
    throw new UnsupportedOperationException("Not supported yet.");
}




}
