/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import conexaobd.Conexaobd;
import conexaobd.Funcionario;
import conexaobd.Login;
import entrada.telaPrincipal;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author 3° Ano Info
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        separador1 = new javax.swing.JSeparator();
        senha = new javax.swing.JPasswordField();
        separador2 = new javax.swing.JSeparator();
        email = new javax.swing.JTextField();
        entra = new javax.swing.JLabel();
        cadastro = new javax.swing.JLabel();
        painelcadastro = new javax.swing.JPanel();
        painelentrar = new javax.swing.JPanel();
        fechar = new javax.swing.JLabel();
        userimg = new javax.swing.JLabel();
        cadeadoimg = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        logoden = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(45, 130, 181));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(separador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 220, -1));

        senha.setBackground(new java.awt.Color(45, 130, 181));
        senha.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        senha.setForeground(new java.awt.Color(255, 255, 255));
        senha.setText("Password");
        senha.setBorder(null);
        senha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                senhaFocusGained(evt);
            }
        });
        jPanel4.add(senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 220, 30));
        jPanel4.add(separador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 220, 10));

        email.setBackground(new java.awt.Color(45, 130, 181));
        email.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setText("E-mail");
        email.setBorder(null);
        email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFocusGained(evt);
            }
        });
        jPanel4.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 220, 30));

        entra.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        entra.setForeground(new java.awt.Color(255, 255, 255));
        entra.setText("            Entrar");
        entra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entraMouseClicked(evt);
            }
        });
        jPanel4.add(entra, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 110, 28));

        cadastro.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        cadastro.setForeground(new java.awt.Color(255, 255, 255));
        cadastro.setText("     Cadastre-se");
        cadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastroMouseClicked(evt);
            }
        });
        jPanel4.add(cadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 97, 28));

        painelcadastro.setBackground(new java.awt.Color(45, 130, 181));
        painelcadastro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout painelcadastroLayout = new javax.swing.GroupLayout(painelcadastro);
        painelcadastro.setLayout(painelcadastroLayout);
        painelcadastroLayout.setHorizontalGroup(
            painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 97, Short.MAX_VALUE)
        );
        painelcadastroLayout.setVerticalGroup(
            painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        jPanel4.add(painelcadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, 30));

        painelentrar.setBackground(new java.awt.Color(45, 130, 181));
        painelentrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout painelentrarLayout = new javax.swing.GroupLayout(painelentrar);
        painelentrar.setLayout(painelentrarLayout);
        painelentrarLayout.setHorizontalGroup(
            painelentrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        painelentrarLayout.setVerticalGroup(
            painelentrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        jPanel4.add(painelentrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, 30));

        fechar.setBackground(new java.awt.Color(1, 89, 146));
        fechar.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        fechar.setForeground(new java.awt.Color(1, 89, 146));
        fechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/fechar-simbolo-de-botao-circular.png"))); // NOI18N
        fechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fecharMouseClicked(evt);
            }
        });
        jPanel4.add(fechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        userimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/user (4).png"))); // NOI18N
        jPanel4.add(userimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-200, 90, 280, 40));

        cadeadoimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/cadeado.png"))); // NOI18N
        jPanel4.add(cadeadoimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-200, 140, 270, 40));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 340, 380));

        jPanel5.setBackground(new java.awt.Color(1, 89, 146));

        logoden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/25.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(logoden)
                .addContainerGap(122, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(logoden)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fecharMouseClicked
        dispose();
    }//GEN-LAST:event_fecharMouseClicked

    private void emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusGained
        email.setText("");
    }//GEN-LAST:event_emailFocusGained

    private void senhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_senhaFocusGained
        senha.setText("");
    }//GEN-LAST:event_senhaFocusGained

    private void cadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastroMouseClicked
        
        new registro().setVisible(true);
    }//GEN-LAST:event_cadastroMouseClicked

    private void entraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entraMouseClicked
        
        Login login = new Login();
        Conexaobd conexao = new Conexaobd();
    
        boolean sessao = login.Login(email.getText(), senha.getText());
        
        if (sessao != false){
          
            new telaPrincipal().setVisible(true);
            dispose();
        }else {
            JOptionPane.showMessageDialog(null, "Dados Inválidos!");
        }
       
    }//GEN-LAST:event_entraMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cadastro;
    private javax.swing.JLabel cadeadoimg;
    private javax.swing.JTextField email;
    private javax.swing.JLabel entra;
    private javax.swing.JLabel fechar;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel logoden;
    private javax.swing.JPanel painelcadastro;
    private javax.swing.JPanel painelentrar;
    private javax.swing.JPasswordField senha;
    private javax.swing.JSeparator separador1;
    private javax.swing.JSeparator separador2;
    private javax.swing.JLabel userimg;
    // End of variables declaration//GEN-END:variables
}
